(function() {
	console.log(`PERFORMANCE START: ${performance.now()}`);
var phoneIds = ["page1406"];
var tabletIds = ["page1406"];
var phone = {
  "ctx1405" : function() { return {"uniqueId":"page1406","name":"Page 1","contextId":"ctx1405","ctxId":"ctx1405","cacheMode":"persist/persist","controls":[{"id":"mc1409","type":"panel","styleSetIds":["mc1409disp"],"direction":"vertical","scroll":false,"grow":1,"panelType":"body","isForm":false,"collapsible":false,"isModal":false,"controls":[{"id":"mc1408","type":"panel","styleSetIds":["mc1409disp_panel","dss_header","dss_no_margin_child","dss_grouping_grow","dss_primBgCol","mc1408disp"],"direction":"horizontal","scroll":false,"grow":0,"panelType":"header","isForm":false,"collapsible":false,"controls":[{"id":"mc1410","mcClass":"back-button","type":"button","styleSetIds":["dss_header_button","dss_no_margin_child_button","dss_grouping_grow_button","dss_primBgCol_button","mc1408disp_button","dss_header_square","dss_header_any","dss_allButton","dss_textButton","dss_roundedButton","dss_squareButton","dss_centerIconButton","dss_capitalize_transform_text","mc1410disp"],"name":"","icon":"fa fa-chevron-left","alt":{"id":"mc1410","isBox":true,"type":"content","styleSetIds":["dss_header_content","dss_grouping_grow_content","dss_no_margin_child_content","mc1disp_content","dss_header_any","dss_header_square","mc2disp"],"value":""}},{"id":"mc1411","type":"content","styleSetIds":["dss_header_content","dss_no_margin_child_content","dss_grouping_grow_content","dss_primBgCol_content","mc1408disp_content","dss_header_any","dss_text_overflow","dss_grow","dss_primText","dss_center_grow","mc1411disp"],"value":"{APP-NAME}","alt":{"id":"mc1411","isBox":true,"type":"content","styleSetIds":["dss_header_content","dss_grouping_grow_content","dss_no_margin_child_content","mc1disp_content","dss_header_any","dss_grow","mc3disp"],"value":""}},{"id":"mc1414","type":"panel","styleSetIds":["dss_header_panel","dss_no_margin_child_panel","dss_grouping_grow_panel","dss_primBgCol_panel","mc1408disp_panel","dss_header_space","dss_header_any","mc1414disp"],"direction":"horizontal","scroll":false,"grow":0,"panelType":"inTemplate","isForm":false,"collapsible":false},{"id":"mc1415","isBox":true,"type":"content","styleSetIds":["dss_header_content","dss_no_margin_child_content","dss_grouping_grow_content","dss_primBgCol_content","mc1408disp_content","dss_header_any","dss_header_square","mc1415disp"],"value":""}],"dock":"top"},{"id":"mc1407","type":"panel","styleSetIds":["mc1409disp_panel","mc1407disp"],"direction":"vertical","scroll":true,"grow":1,"isForm":false,"collapsible":false,"controls":[{"id":"mc1425","eta":{"setText":{}},"type":"textbox","styleSetIds":["mc1407disp_textbox","dss_dropdown_std","dss_stdInput","dss_input_full","mc1425disp"],"incrementalType":false},{"id":"mc1430","eta":{"setText":{}},"type":"textbox","styleSetIds":["mc1407disp_textbox","dss_dropdown_std","dss_stdInput","dss_input_full","mc1430disp"],"incrementalType":false}],"panelType":"main"}]}]}; }
};
var tablet = {

};
Capriza.structManager = {
  getStruct : function(ctxId, isTablet) { return ((isTablet && tablet[ctxId]) || phone[ctxId])(); },
  getUniqueIds : function(isTablet) { return isTablet ? tabletIds : phoneIds; },
  getContextIds : function() { return Object.keys(phone); }
};
})();